# This is the working updated yaml file whose workflow is:
  # 1. Whenever changes are pushed or merged to main branch the workflow will start
  # 2. Update the image in the azure container registry
  # 3. Deploy the latest changes in the container apps

  # In this, the code to deploy is not directly in the root of the github repo. It is inside a subfolder: 7_dockerizing_a_node_app/Dockerfile

name: Trigger auto deployment for mycaci101

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mycaci101-AutoDeployTrigger-d63f7ce6-7902-4744-8542-ea7a6f3abdfe.yml'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MYCACI101_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYCACI101_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYCACI101_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/7_dockerizing_a_node_app
          _dockerfilePathKey_: ${{ github.workspace }}/7_dockerizing_a_node_app/Dockerfile
          registryUrl: mycrci101.azurecr.io
          registryUsername: ${{ secrets.MYCACI101_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYCACI101_REGISTRY_PASSWORD }}
          containerAppName: mycaci101
          resourceGroup: my-rg-101
          imageToBuild: mycrci101.azurecr.io/mycaci101:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
